[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-test-app/0 [idle] active: received database credentials of the first database
  postgresql-test-app/1 [idle] active: received database credentials of the first database
  database/0 [executing] active: Primary
  database/1 [executing] active: 
  database/2 [executing] active: 
  another-database/0 [idle] active: Primary
  another-database/1 [idle] active: 
  another-database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:2301 Deploying ch:amd64/jammy/data-integrator-78
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  another-data-integrator/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [executing] blocked: Please relate the data-integrator with the desired product
  another-data-integrator/0 [executing] blocked: Please specify either topic, index, or database name
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [idle] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [idle] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [executing] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [idle] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [idle] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [executing] active: 
  database/2 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/1 [idle] active: 
  database/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.7    unsupported  02:08:12Z

App                      Version  Status   Scale  Charm                Channel        Rev  Address         Exposed  Message
another-application               active       1  postgresql-test-app  latest/edge    388  10.152.183.123  no       received database credentials of the first database
another-data-integrator           blocked      1  data-integrator      latest/stable   78  10.152.183.69   no       Please relate the data-integrator with the desired product
another-database         14.18    active       3  postgresql-k8s                        1  10.152.183.170  no       
data-integrator                   blocked      1  data-integrator      latest/stable   78  10.152.183.174  no       Please relate the data-integrator with the desired product
database                 14.18    active       3  postgresql-k8s                        0  10.152.183.226  no       
postgresql-test-app               active       2  postgresql-test-app  latest/edge    388  10.152.183.44   no       received database credentials of the first database

Unit                        Workload  Agent  Address     Ports  Message
another-application/0*      active    idle   10.1.25.22         received database credentials of the first database
another-data-integrator/0*  blocked   idle   10.1.25.26         Please relate the data-integrator with the desired product
another-database/0*         active    idle   10.1.25.15         Primary
another-database/1          active    idle   10.1.25.18         
another-database/2          active    idle   10.1.25.16         
data-integrator/0*          blocked   idle   10.1.25.25         Please relate the data-integrator with the desired product
database/0*                 active    idle   10.1.25.19         Primary
database/1                  active    idle   10.1.25.24         
database/2                  active    idle   10.1.25.23         
postgresql-test-app/0*      active    idle   10.1.25.8          received database credentials of the first database
postgresql-test-app/1       active    idle   10.1.25.9          received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

unit-another-database-2: 01:42:23 ERROR unit.another-database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-another-database-2: 01:42:51 ERROR unit.another-database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-another-application-0: 01:53:31 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-database-0: 01:53:34 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-1: 01:53:34 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-test-app-1: 01:53:34 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-test-app-0: 01:53:34 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-2: 01:53:35 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-0: 01:53:35 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-database-0: 02:05:51 ERROR unit.database/0.juju-log database:20: Invalid extra user roles: test
unit-database-0: 02:05:52 ERROR unit.database/0.juju-log database:20: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 107, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 309, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
unit-database-0: 02:05:56 ERROR unit.database/0.juju-log database:21: Invalid extra user roles: test
unit-database-0: 02:05:56 ERROR unit.database/0.juju-log database:21: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 107, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 309, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles

[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...