[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:493 starting continuous writes to the database
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:496 checking whether writes are increasing
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:243 Initial writes {'test.postgresql-k8s-0': 178, 'test.postgresql-k8s-2': 179}
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:249 Retry writes {'test.postgresql-k8s-0': 315, 'test.postgresql-k8s-2': 316}
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:500 scaling out the first cluster
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s (waiting for exactly 4 units, current : 3)
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: Primary
  postgresql-k8s/3 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [executing] active: 
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: Primary
  postgresql-k8s/3 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: Primary
  postgresql-k8s/3 [idle] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/3 [idle] active: 
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:504 checking whether writes are increasing
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test-other/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:243 Initial writes {'test.postgresql-k8s-0': 15598, 'test.postgresql-k8s-2': 15600, 'test-other.postgresql-k8s-0': 15601}
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test-other/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:249 Retry writes {'test.postgresql-k8s-0': 15712, 'test.postgresql-k8s-2': 15714, 'test-other.postgresql-k8s-0': 15714}
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:507 scaling out the second cluster
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s (waiting for exactly 4 units, current : 3)
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [executing] active: Standby
  postgresql-k8s/1 [executing] active: 
  postgresql-k8s/2 [executing] active: 
  postgresql-k8s/3 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: Standby
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: 
  postgresql-k8s/3 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: Standby
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: 
  postgresql-k8s/3 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: Standby
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: 
  postgresql-k8s/3 [idle] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: Standby
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: 
  postgresql-k8s/3 [idle] active: 
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:513 checking whether writes are increasing
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test-other/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:243 Initial writes {'test.postgresql-k8s-0': 22460, 'test.postgresql-k8s-2': 22462, 'test-other.postgresql-k8s-0': 22463}
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test-other/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:249 Retry writes {'test.postgresql-k8s-0': 22566, 'test.postgresql-k8s-2': 22567, 'test-other.postgresql-k8s-0': 22569}
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:516 scaling in the first cluster
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s (waiting for exactly 3 units, current : 4)
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s (waiting for exactly 3 units, current : 4)
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: Primary
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:519 checking whether writes are increasing
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test-other/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:243 Initial writes {'test.postgresql-k8s-0': 25069, 'test.postgresql-k8s-2': 25070, 'test-other.postgresql-k8s-0': 25072}
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test-other/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:249 Retry writes {'test.postgresql-k8s-0': 25161, 'test.postgresql-k8s-2': 25162, 'test-other.postgresql-k8s-0': 25164}
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:522 scaling in the second cluster
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s (waiting for exactly 3 units, current : 4)
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s (waiting for exactly 3 units, current : 4)
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: Standby
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:527 checking whether writes are increasing
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test-other/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:243 Initial writes {'test.postgresql-k8s-0': 28138, 'test.postgresql-k8s-2': 28140, 'test-other.postgresql-k8s-0': 28141}
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test-other/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:249 Retry writes {'test.postgresql-k8s-0': 28234, 'test.postgresql-k8s-2': 28236, 'test-other.postgresql-k8s-0': 28237}
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:532 checking whether no writes were lost
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1038 HTTP Request: GET https://10.1.1.115:16443/api/v1/namespaces/test-other/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:86 Destroying second model
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.6    unsupported  02:04:39Z

App                  Version  Status  Scale  Charm                Channel      Rev  Address         Exposed  Message
postgresql-k8s       14.13    active      3  postgresql-k8s                      0  10.152.183.101  no       Primary
postgresql-test-app           active      1  postgresql-test-app  latest/edge  305  10.152.183.48   no       received database credentials of the first database

Unit                    Workload  Agent      Address       Ports  Message
postgresql-k8s/0        active    executing  10.1.236.206         
postgresql-k8s/1        active    executing  10.1.236.215         
postgresql-k8s/2*       active    executing  10.1.236.205         Primary
postgresql-test-app/0*  active    idle       10.1.236.213         received database credentials of the first database

Offer              Application     Charm           Rev  Connected  Endpoint           Interface         Role
replication        postgresql-k8s  postgresql-k8s  0    0/0        replication        postgresql_async  requirer
replication-offer  postgresql-k8s  postgresql-k8s  0    1/1        replication-offer  postgresql_async  provider

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-postgresql-k8s-0: 01:45:46 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6319e277-17d6-49a5-8757-b0783f135cab:r#5#remote-caed7731539f42b38cb2fbe6599c351c": settings 6319e277-17d6-49a5-8757-b0783f135cab:r#5#remote-caed7731539f42b38cb2fbe6599c351c not found (not found)
unit-postgresql-k8s-1: 01:45:47 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6319e277-17d6-49a5-8757-b0783f135cab:r#5#remote-caed7731539f42b38cb2fbe6599c351c": settings 6319e277-17d6-49a5-8757-b0783f135cab:r#5#remote-caed7731539f42b38cb2fbe6599c351c not found (not found)
unit-postgresql-k8s-1: 01:50:36 ERROR unit.postgresql-k8s/1.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-postgresql-k8s-0: 02:02:52 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:02:52 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:02:53 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:02:53 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:02:58 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:02:58 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:03 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:03 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:03 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:03 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:03:08 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:03:08 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:12 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:12 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:14 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:14 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:03:17 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:03:17 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:24 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:24 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:25 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:25 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:03:27 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:03:27 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:30 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:30 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:33 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:33 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:03:36 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:03:36 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:41 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:41 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:44 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:44 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:03:48 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:03:48 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:51 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:03:51 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:52 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:03:52 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:04:00 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:04:00 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:04:00 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:04:00 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:04:00 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:04:00 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:04:08 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:04:08 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:04:09 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:04:09 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:04:09 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:04:09 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:04:18 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:04:18 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:04:19 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:04:19 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:04:19 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:04:19 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:04:28 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-2: 02:04:28 ERROR unit.postgresql-k8s/2.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:04:29 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-1: 02:04:29 ERROR unit.postgresql-k8s/1.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:04:30 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service get failed: services "postgresql-k8s" not found
unit-postgresql-k8s-0: 02:04:30 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: services "postgresql-k8s" not found

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...